# MOCKUP FOR YAML TEMPLATE PARSING AND TESTING

# Playbook schema version, required
version: 1

# Paper trading, default is `true`
dryrun: true

# Subscriptions
subscription:
  ethbtc4hBuy:
    action:
      - orderEthbtcBuy.execute(OrderAction.Create)
    chart: ethbtc4h
    condition:
      - [total, '=>', 0]
    timeframeAny:
      - timeframeRsi14BullishOversold

# Analysis
analysis:
  analysisRsi14:
    config:
      inRealField: close
      optInTimePeriod: 14
      startIndex: 14
    type: RSI

# Assets
asset:
  btc:
    exchange: paper
    symbol: btc
  eth:
    exchange: paper
    symbol: eth

# Charts
chart:
  ethbtc4h:
    exchange: paper
    pair: ethbtc
    pollTime: 5m # 300
    candleTime: 4h # 14400

# Exchanges
exchange:
  paper:
  kraken:

# Orders
order:
  orderEthbtcBuy:
    amount: 10%
    exchange: paper
    pair: ethbtc
    position: ethbtc
    side: buy
    type: market
    # type: limit:-5%

# Positions
position:
  ethbtc:
    exchange: paper
    pair: ethbtc

# Pairs
pair:
  ethbtc:
    a: eth
    b: btc

# Scenarios
scenario:
  scenarioRsi14BullishOversold:
    analysis:
      - analysisRsi14
    condition:
      -
        # Previous candle
        - [outReal, '<=', 30]

        # Latest candle
        - [outReal, '>=', 30]

# Strategies
strategy:
  strat11111:
    action:
      - [scenarioRsi14BullishOversold]
    analysis:
      - analysisRsi14
    chart: ethbtc4h
  stratRsi14BullishOversold:
    action:
      - [scenarioRsi14BullishOversold, strat11111]
    analysis:
      - analysisRsi14
    chart: ethbtc4h

# Timeframes
timeframe:
  timeframeRsi14BullishOversold:
    intervalTime: 1000
    keepalive: false # Runs once
    strategy:
      - stratRsi14BullishOversold
    windowTime: 50d # 86400000 * 50